description = "Split one file into multiple smaller files."
author = "Localt"
license = "MIT"
binary_url = "https://raw.githubusercontent.com/Localtings/C-File-Splitter/main/bin/filesplitter.exe"
checksum = "cd09432e17a3196e76b1f7793848f67f30fbd035c5d26e910754f95c16b0808b"
