[[package]]
name = "filesplitter"
description = "Split one file into multiple smaller files."
license = "MIT"

[[package.release]]
version = "1.0.0"
binary_url = "https://raw.githubusercontent.com/Localtings/C-File-Splitter/main/bin/filesplitter.exe"

[[package.release]]
version = "1.0.1"
binary_url = "https://raw.githubusercontent.com/Localtings/C-File-Splitter/main/bin/filesplitter.exe"
